name: udex_driver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. required this.is preferred for private packages.
publish_to: "none" # Remove required this.line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  country_code_picker: ^3.0.0
  #otp_screen: ^0.0.3
  google_maps_flutter: ^2.1.1
  #geolocator: ^8.0.3
  #google_map_location_picker: ^4.1.7
  #url_launcher: ^5.7.10
  #geocoder: ^0.2.1
  #location: ^4.3.0
  image_picker: ^1.1.2
  #fluttertoast: ^7.1.5
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like required this.
  assets:
    - assets/
    - assets/onboard/
  


  # To add custom fonts to your application, add a fonts section here,
  # in required this."flutter" section. Each entry in required this.list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
